function scenario_case(handles,sys,data)
r2d = 180/pi;
switch sys.case
    case 0
        set(handles.text_missile_title_N,'enable','off');
        set(handles.edit_missile_N,'enable','off');
        set(handles.text_missile_unit_N,'enable','off');
        set(handles.text_missile_title_No,'enable','off');
        set(handles.popupmenu_missile_No,'enable','off');
        set(handles.text_missile_unit_No,'enable','off');
        set(handles.text_missile_title_X,'enable','off');
        set(handles.edit_missile_X,'enable','off');
        set(handles.text_missile_unit_X,'enable','off');
        set(handles.text_missile_title_Y,'enable','off');
        set(handles.edit_missile_Y,'enable','off');
        set(handles.text_missile_unit_Y,'enable','off');
        set(handles.text_missile_title_Z,'enable','off');
        set(handles.edit_missile_Z,'enable','off');
        set(handles.text_missile_unit_Z,'enable','off');
        set(handles.text_missile_title_V,'enable','off');
        set(handles.edit_missile_V,'enable','off');
        set(handles.text_missile_unit_V,'enable','off');
        set(handles.text_missile_title_psi,'enable','off');
        set(handles.edit_missile_psi,'enable','off');
        set(handles.text_missile_unit_psi,'enable','off');
        set(handles.text_missile_title_P_rt,'enable','off');
        set(handles.edit_missile_P_rt,'enable','off');
        set(handles.text_missile_unit_P_rt,'enable','off');
        set(handles.text_missile_title_G_rt,'enable','off');
        set(handles.edit_missile_G_rt,'enable','off');
        set(handles.text_missile_unit_G_rt,'enable','off');
        set(handles.text_missile_title_G_rr,'enable','off');
        set(handles.edit_missile_G_rr,'enable','off');
        set(handles.text_missile_unit_G_rr,'enable','off');
        set(handles.text_missile_title_F,'enable','off');
        set(handles.edit_missile_F,'enable','off');
        set(handles.text_missile_unit_F,'enable','off');
        set(handles.text_missile_title_FoV_lim,'enable','off');
        set(handles.edit_missile_FoV_lim,'enable','off');
        set(handles.text_missile_unit_FoV_lim,'enable','off');
        
        set(handles.text_decoy_title_N,'enable','off');
        set(handles.edit_decoy_N,'enable','off');
        set(handles.text_decoy_unit_N,'enable','off');
        set(handles.text_decoy_title_No,'enable','off');
        set(handles.popupmenu_decoy_No,'enable','off');
        set(handles.text_decoy_unit_No,'enable','off');
        set(handles.text_decoy_title_V,'enable','off');
        set(handles.edit_decoy_V,'enable','off');
        set(handles.text_decoy_unit_V,'enable','off');
        set(handles.text_decoy_title_psi,'enable','off');
        set(handles.edit_decoy_psi,'enable','off');
        set(handles.text_decoy_unit_psi,'enable','off');
        set(handles.text_decoy_title_Z,'enable','off');
        set(handles.edit_decoy_Z,'enable','off');
        set(handles.text_decoy_unit_Z,'enable','off');
        set(handles.text_decoy_title_P_jt,'enable','off');
        set(handles.edit_decoy_P_jt,'enable','off');
        set(handles.text_decoy_unit_P_jt,'enable','off');
        set(handles.text_decoy_title_G_jt,'enable','off');
        set(handles.edit_decoy_G_jt,'enable','off');
        set(handles.text_decoy_unit_G_jt,'enable','off');
        set(handles.text_decoy_title_G_rr,'enable','off');
        set(handles.edit_decoy_G_rr,'enable','off');
        set(handles.text_decoy_unit_G_rr,'enable','off');
        set(handles.text_decoy_title_F,'enable','off');
        set(handles.edit_decoy_F,'enable','off');
        set(handles.text_decoy_unit_F,'enable','off');
        set(handles.text_decoy_title_RCS,'enable','off');
        set(handles.edit_decoy_RCS,'enable','off');
        set(handles.text_decoy_unit_RCS,'enable','off');
        
        set(handles.text_ship_title_V,'enable','off');
        set(handles.edit_ship_V,'enable','off');
        set(handles.text_ship_unit_V,'enable','off');
        set(handles.text_ship_title_psi,'enable','off');
        set(handles.edit_ship_psi,'enable','off');
        set(handles.text_ship_unit_psi,'enable','off');
        set(handles.text_ship_title_RCS,'enable','off');
        set(handles.edit_ship_RCS,'enable','off');
        set(handles.text_ship_unit_RCS,'enable','off');
        
        set(handles.text_missile_title_itN,'enable','off')
        set(handles.edit_missile_itN,'enable','off')
        set(handles.text_missile_unit_itN,'enable','off')
        set(handles.text_missile_title_R,'enable','off')
        set(handles.edit_missile_R,'enable','off')
        set(handles.text_missile_unit_R,'enable','off')
        set(handles.text_missile_title_theta,'enable','off')
        set(handles.edit_missile_theta,'enable','off')
        set(handles.text_missile_unit_theta,'enable','off')
        set(handles.text_missile_title_dtheta1,'enable','off')
        set(handles.edit_missile_dtheta1,'enable','off')
        set(handles.text_missile_unit_dtheta1,'enable','off')
        set(handles.text_missile_title_dtheta2,'enable','off')
        set(handles.edit_missile_dtheta2,'enable','off')
        set(handles.text_missile_unit_dtheta2,'enable','off')
        
    case 1
        set(handles.text_missile_title_N,'enable','on',...
            'string','미사일 수(최대 3기):');
        set(handles.edit_missile_N,'enable','on',...
            'string',num2str(data.C.missile(1).N));
        set(handles.text_missile_unit_N,'enable','on');
        set(handles.text_missile_title_No,'enable','on');
        set(handles.popupmenu_missile_No,'enable','on',...
            'string',num2str([1:data.C.missile(1).N]'));
        set(handles.text_missile_unit_No,'enable','on');
        set(handles.text_missile_title_X,'enable','on');
        set(handles.edit_missile_X,'enable','on',...
            'string',num2str(data.C.missile(1).X));
        set(handles.text_missile_unit_X,'enable','on');
        set(handles.text_missile_title_Y,'enable','on');
        set(handles.edit_missile_Y,'enable','on',...
            'string',num2str(data.C.missile(1).Y));
        set(handles.text_missile_unit_Y,'enable','on');
        set(handles.text_missile_title_Z,'enable','on');
        set(handles.edit_missile_Z,'enable','on',...
            'string',num2str(data.C.missile(1).Z));
        set(handles.text_missile_unit_Z,'enable','on');
        set(handles.text_missile_title_V,'enable','on');
        set(handles.edit_missile_V,'enable','on',...
            'string',num2str(data.C.missile(1).V));
        set(handles.text_missile_unit_V,'enable','on');
        set(handles.text_missile_title_psi,'enable','on');
        set(handles.edit_missile_psi,'enable','on',...
            'string',num2str(data.C.missile(1).psi*r2d));
        set(handles.text_missile_unit_psi,'enable','on');
        set(handles.text_missile_title_P_rt,'enable','on');
        set(handles.edit_missile_P_rt,'enable','on',...
            'string',num2str(data.C.missile(1).P_rt*10^6));
        set(handles.text_missile_unit_P_rt,'enable','on');
        set(handles.text_missile_title_G_rt,'enable','on');
        set(handles.edit_missile_G_rt,'enable','on',...
            'string',num2str(data.C.missile(1).G_rt));
        set(handles.text_missile_unit_G_rt,'enable','on');
        set(handles.text_missile_title_G_rr,'enable','on');
        set(handles.edit_missile_G_rr,'enable','on',...
            'string',num2str(data.C.missile(1).G_rr));
        set(handles.text_missile_unit_G_rr,'enable','on');
        set(handles.text_missile_title_F,'enable','on');
        set(handles.edit_missile_F,'enable','on',...
            'string',num2str(data.C.missile(1).F));
        set(handles.text_missile_unit_F,'enable','on');
        set(handles.text_missile_title_FoV_lim,'enable','on');
        set(handles.edit_missile_FoV_lim,'enable','on',...
            'string',num2str(data.C.missile(1).FoV_lim*r2d));
        set(handles.text_missile_unit_FoV_lim,'enable','on');
        set(handles.text_decoy_title_N,'enable','off',...
            'string','기만기 수(최대 1기):');
        set(handles.edit_decoy_N,'enable','off',...
            'string',num2str(data.C.decoy(1).N));
        set(handles.text_decoy_unit_N,'enable','off');
        set(handles.text_decoy_title_No,'enable','off');
        set(handles.popupmenu_decoy_No,'enable','off',...
            'string',num2str([1:data.C.decoy(1).N]'));
        set(handles.text_decoy_unit_No,'enable','off');
        set(handles.text_decoy_title_V,'enable','off');
        set(handles.edit_decoy_V,'enable','off',...
            'string',num2str(data.C.decoy(1).V));
        set(handles.text_decoy_unit_V,'enable','off');
        set(handles.text_decoy_title_psi,'enable','off');
        set(handles.edit_decoy_psi,'enable','off',...
            'string',num2str(data.C.decoy(1).lau_psi*r2d));
        set(handles.text_decoy_unit_psi,'enable','off');
        set(handles.text_decoy_title_Z,'enable','off');
        set(handles.edit_decoy_Z,'enable','off',...
            'string',num2str(data.C.decoy(1).Z));
        set(handles.text_decoy_unit_Z,'enable','off');
        set(handles.text_decoy_title_P_jt,'enable','on');
        set(handles.edit_decoy_P_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).P_jt*10^6));
        set(handles.text_decoy_unit_P_jt,'enable','on');
        set(handles.text_decoy_title_G_jt,'enable','on');
        set(handles.edit_decoy_G_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).G_jt));
        set(handles.text_decoy_unit_G_jt,'enable','on');
        set(handles.text_decoy_title_G_rr,'enable','on');
        set(handles.edit_decoy_G_rr,'enable','on',...
            'string',num2str(data.C.decoy(1).G_rr));
        set(handles.text_decoy_unit_G_rr,'enable','on');
        set(handles.text_decoy_title_F,'enable','on');
        set(handles.edit_decoy_F,'enable','on',...
            'string',num2str(data.C.decoy(1).F));
        set(handles.text_decoy_unit_F,'enable','on');
        set(handles.edit_decoy_RCS,...
            'string',num2str(data.C.decoy(1).RCS));
                
        set(handles.text_ship_title_V,'enable','on');
        set(handles.edit_ship_V,'enable','on',...
            'string',num2str(data.C.ship(1).V));
        set(handles.text_ship_unit_V,'enable','on');
        set(handles.text_ship_title_psi,'enable','on');
        set(handles.edit_ship_psi,'enable','on',...
            'string',num2str(data.C.ship(1).psi*r2d));
        set(handles.text_ship_unit_psi,'enable','on');
        set(handles.text_ship_title_RCS,'enable','on');
        set(handles.edit_ship_RCS,'enable','on',...
            'string',num2str(data.C.ship(1).RCS));
        set(handles.text_ship_unit_RCS,'enable','on');
        
        if sys.flag_MC == 0
            set(handles.text_missile_title_itN,'enable','off')
            set(handles.edit_missile_itN,'enable','off')
            set(handles.text_missile_unit_itN,'enable','off')
            set(handles.text_missile_title_R,'enable','off')
            set(handles.edit_missile_R,'enable','off')
            set(handles.text_missile_unit_R,'enable','off')
            set(handles.text_missile_title_theta,'enable','off')
            set(handles.edit_missile_theta,'enable','off')
            set(handles.text_missile_unit_theta,'enable','off')
            set(handles.text_missile_title_dtheta1,'enable','off')
            set(handles.edit_missile_dtheta1,'enable','off')
            set(handles.text_missile_unit_dtheta1,'enable','off')
            set(handles.text_missile_title_dtheta2,'enable','off')
            set(handles.edit_missile_dtheta2,'enable','off')
            set(handles.text_missile_unit_dtheta2,'enable','off')
        else
            set(handles.text_missile_title_itN,'enable','on')
            set(handles.edit_missile_itN,'enable','on',...
                'string',num2str(data.iter.N))
            set(handles.text_missile_unit_itN,'enable','on')
            set(handles.text_missile_title_R,'enable','on')
            set(handles.edit_missile_R,'enable','on',...
                'string',num2str(data.iter.R))
            set(handles.text_missile_unit_R,'enable','on')
            set(handles.text_missile_title_theta,'enable','on')
            set(handles.edit_missile_theta,'enable','inactive',...
                'string','0:ΔΘ1:2π')
            set(handles.text_missile_unit_theta,'enable','on')
            set(handles.text_missile_title_dtheta1,'enable','on')
            set(handles.edit_missile_dtheta1,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta1,'enable','on')
            set(handles.text_missile_title_dtheta2,'enable','on')
            set(handles.edit_missile_dtheta2,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta2,'enable','on')
        end
    case 2
        set(handles.text_missile_title_N,'enable','on',...
            'string','미사일 수(최대 3기):');
        set(handles.edit_missile_N,'enable','on',...
            'string',num2str(data.C.missile(1).N));
        set(handles.text_missile_unit_N,'enable','on');
        set(handles.text_missile_title_No,'enable','on');
        set(handles.popupmenu_missile_No,'enable','on',...
            'string',num2str([1:data.C.missile(1).N]'));
        set(handles.text_missile_unit_No,'enable','on');
        set(handles.text_missile_title_X,'enable','on');
        set(handles.edit_missile_X,'enable','on',...
            'string',num2str(data.C.missile(1).X));
        set(handles.text_missile_unit_X,'enable','on');
        set(handles.text_missile_title_Y,'enable','on');
        set(handles.edit_missile_Y,'enable','on',...
            'string',num2str(data.C.missile(1).Y));
        set(handles.text_missile_unit_Y,'enable','on');
        set(handles.text_missile_title_Z,'enable','on');
        set(handles.edit_missile_Z,'enable','on',...
            'string',num2str(data.C.missile(1).Z));
        set(handles.text_missile_unit_Z,'enable','on');
        set(handles.text_missile_title_V,'enable','on');
        set(handles.edit_missile_V,'enable','on',...
            'string',num2str(data.C.missile(1).V));
        set(handles.text_missile_unit_V,'enable','on');
        set(handles.text_missile_title_psi,'enable','on');
        set(handles.edit_missile_psi,'enable','on',...
            'string',num2str(data.C.missile(1).psi*r2d));
        set(handles.text_missile_unit_psi,'enable','on');
        set(handles.text_missile_title_P_rt,'enable','on');
        set(handles.edit_missile_P_rt,'enable','on',...
            'string',num2str(data.C.missile(1).P_rt*10^6));
        set(handles.text_missile_unit_P_rt,'enable','on');
        set(handles.text_missile_title_G_rt,'enable','on');
        set(handles.edit_missile_G_rt,'enable','on',...
            'string',num2str(data.C.missile(1).G_rt));
        set(handles.text_missile_unit_G_rt,'enable','on');
        set(handles.text_missile_title_G_rr,'enable','on');
        set(handles.edit_missile_G_rr,'enable','on',...
            'string',num2str(data.C.missile(1).G_rr));
        set(handles.text_missile_unit_G_rr,'enable','on');
        set(handles.text_missile_title_F,'enable','on');
        set(handles.edit_missile_F,'enable','on',...
            'string',num2str(data.C.missile(1).F));
        set(handles.text_missile_unit_F,'enable','on');
        set(handles.text_missile_title_FoV_lim,'enable','on');
        set(handles.edit_missile_FoV_lim,'enable','on',...
            'string',num2str(data.C.missile(1).FoV_lim*r2d));
        set(handles.text_missile_unit_FoV_lim,'enable','on');
        
        set(handles.text_decoy_title_N,'enable','off',...
            'string','기만기 수(최대 1기):');
        set(handles.edit_decoy_N,'enable','off',...
            'string','1');
        set(handles.text_decoy_unit_N,'enable','off');
        set(handles.text_decoy_title_No,'enable','off');
        set(handles.popupmenu_decoy_No,'enable','off');
        set(handles.text_decoy_unit_No,'enable','off');
        set(handles.text_decoy_title_V,'enable','off');
        set(handles.edit_decoy_V,'enable','off',...
            'string','0');
        set(handles.text_decoy_unit_V,'enable','off');
        set(handles.text_decoy_title_psi,'enable','off');
        set(handles.edit_decoy_psi,'enable','off',...
            'string','0');
        set(handles.text_decoy_unit_psi,'enable','off');
        set(handles.text_decoy_title_Z,'enable','on');
        set(handles.edit_decoy_Z,'enable','on',...
            'string','30');
        set(handles.text_decoy_unit_Z,'enable','on');
        set(handles.text_decoy_title_P_jt,'enable','on');
        set(handles.edit_decoy_P_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).P_jt*10^6));
        set(handles.text_decoy_unit_P_jt,'enable','on');
        set(handles.text_decoy_title_G_jt,'enable','on');
        set(handles.edit_decoy_G_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).G_jt));
        set(handles.text_decoy_unit_G_jt,'enable','on');
        set(handles.text_decoy_title_G_rr,'enable','on');
        set(handles.edit_decoy_G_rr,'enable','on',...
            'string',num2str(data.C.decoy(1).G_rr));
        set(handles.text_decoy_unit_G_rr,'enable','on');
        set(handles.text_decoy_title_F,'enable','on');
        set(handles.edit_decoy_F,'enable','on',...
            'string',num2str(data.C.decoy(1).F));
        set(handles.text_decoy_unit_F,'enable','on');
        set(handles.edit_decoy_RCS,...
            'string',num2str(data.C.decoy(1).RCS));

        set(handles.text_ship_title_V,'enable','on');
        set(handles.edit_ship_V,'enable','on',...
            'string',num2str(data.C.ship(1).V));
        set(handles.text_ship_unit_V,'enable','on');
        set(handles.text_ship_title_psi,'enable','on');
        set(handles.edit_ship_psi,'enable','on',...
            'string',num2str(data.C.ship(1).psi*r2d));
        set(handles.text_ship_unit_psi,'enable','on');
        set(handles.text_ship_title_RCS,'enable','on');
        set(handles.edit_ship_RCS,'enable','on',...
            'string',num2str(data.C.ship(1).RCS));
        set(handles.text_ship_unit_RCS,'enable','on');
        
        if sys.flag_MC == 0
            set(handles.text_missile_title_itN,'enable','off')
            set(handles.edit_missile_itN,'enable','off')
            set(handles.text_missile_unit_itN,'enable','off')
            set(handles.text_missile_title_R,'enable','off')
            set(handles.edit_missile_R,'enable','off')
            set(handles.text_missile_unit_R,'enable','off')
            set(handles.text_missile_title_theta,'enable','off')
            set(handles.edit_missile_theta,'enable','off')
            set(handles.text_missile_unit_theta,'enable','off')
            set(handles.text_missile_title_dtheta1,'enable','off')
            set(handles.edit_missile_dtheta1,'enable','off')
            set(handles.text_missile_unit_dtheta1,'enable','off')
            set(handles.text_missile_title_dtheta2,'enable','off')
            set(handles.edit_missile_dtheta2,'enable','off')
            set(handles.text_missile_unit_dtheta2,'enable','off')
        else
            set(handles.text_missile_title_itN,'enable','on')
            set(handles.edit_missile_itN,'enable','on',...
                'string',num2str(data.iter.N))
            set(handles.text_missile_unit_itN,'enable','on')
            set(handles.text_missile_title_R,'enable','on')
            set(handles.edit_missile_R,'enable','on',...
                'string',num2str(data.iter.R))
            set(handles.text_missile_unit_R,'enable','on')
            set(handles.text_missile_title_theta,'enable','on')
            set(handles.edit_missile_theta,'enable','inactive',...
                'string','0:ΔΘ1:2π')
            set(handles.text_missile_unit_theta,'enable','on')
            set(handles.text_missile_title_dtheta1,'enable','on')
            set(handles.edit_missile_dtheta1,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta1,'enable','on')
            set(handles.text_missile_title_dtheta2,'enable','on')
            set(handles.edit_missile_dtheta2,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta2,'enable','on')
        end
    case 3
        set(handles.text_missile_title_N,'enable','on',...
            'string','미사일 수(최대 3기):');
        set(handles.edit_missile_N,'enable','on',...
            'string',num2str(data.C.missile(1).N));
        set(handles.text_missile_unit_N,'enable','on');
        set(handles.text_missile_title_No,'enable','on');
        set(handles.popupmenu_missile_No,'enable','on',...
            'string',num2str([1:data.C.missile(1).N]'));
        set(handles.text_missile_unit_No,'enable','on');
        set(handles.text_missile_title_X,'enable','on');
        set(handles.edit_missile_X,'enable','on',...
            'string',num2str(data.C.missile(1).X));
        set(handles.text_missile_unit_X,'enable','on');
        set(handles.text_missile_title_Y,'enable','on');
        set(handles.edit_missile_Y,'enable','on',...
            'string',num2str(data.C.missile(1).Y));
        set(handles.text_missile_unit_Y,'enable','on');
        set(handles.text_missile_title_Z,'enable','on');
        set(handles.edit_missile_Z,'enable','on',...
            'string',num2str(data.C.missile(1).Z));
        set(handles.text_missile_unit_Z,'enable','on');
        set(handles.text_missile_title_V,'enable','on');
        set(handles.edit_missile_V,'enable','on',...
            'string',num2str(data.C.missile(1).V));
        set(handles.text_missile_unit_V,'enable','on');
        set(handles.text_missile_title_psi,'enable','on');
        set(handles.edit_missile_psi,'enable','on',...
            'string',num2str(data.C.missile(1).psi*r2d));
        set(handles.text_missile_unit_psi,'enable','on');
        set(handles.text_missile_title_P_rt,'enable','on');
        set(handles.edit_missile_P_rt,'enable','on',...
            'string',num2str(data.C.missile(1).P_rt*10^6));
        set(handles.text_missile_unit_P_rt,'enable','on');
        set(handles.text_missile_title_G_rt,'enable','on');
        set(handles.edit_missile_G_rt,'enable','on',...
            'string',num2str(data.C.missile(1).G_rt));
        set(handles.text_missile_unit_G_rt,'enable','on');
        set(handles.text_missile_title_G_rr,'enable','on');
        set(handles.edit_missile_G_rr,'enable','on',...
            'string',num2str(data.C.missile(1).G_rr));
        set(handles.text_missile_unit_G_rr,'enable','on');
        set(handles.text_missile_title_F,'enable','on');
        set(handles.edit_missile_F,'enable','on',...
            'string',num2str(data.C.missile(1).F));
        set(handles.text_missile_unit_F,'enable','on');
        set(handles.text_missile_title_FoV_lim,'enable','on');
        set(handles.edit_missile_FoV_lim,'enable','on',...
            'string',num2str(data.C.missile(1).FoV_lim*r2d));
        set(handles.text_missile_unit_FoV_lim,'enable','on');
        
        set(handles.text_decoy_title_N,'enable','off',...
            'string','기만기 수(최대 1기):');
        set(handles.edit_decoy_N,'enable','off',...
            'string','1');
        set(handles.text_decoy_unit_N,'enable','off');
        set(handles.text_decoy_title_No,'enable','off');
        set(handles.popupmenu_decoy_No,'enable','off');
        set(handles.text_decoy_unit_No,'enable','off');
        set(handles.text_decoy_title_V,'enable','on');
        set(handles.edit_decoy_V,'enable','on',...
            'string',num2str(data.C.decoy(1).V));
        set(handles.text_decoy_unit_V,'enable','on');
        set(handles.text_decoy_title_psi,'enable','on');
        set(handles.edit_decoy_psi,'enable','on');
        set(handles.edit_decoy_psi,'enable','on',...
            'string',num2str(data.C.decoy(1).lau_psi*r2d));
        set(handles.text_decoy_title_Z,'enable','on');
        set(handles.edit_decoy_Z,'enable','on',...
            'string','30');
        set(handles.text_decoy_unit_Z,'enable','on');
        set(handles.text_decoy_title_P_jt,'enable','on');
        set(handles.edit_decoy_P_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).P_jt*10^6));
        set(handles.text_decoy_unit_P_jt,'enable','on');
        set(handles.text_decoy_title_G_jt,'enable','on');
        set(handles.edit_decoy_G_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).G_jt));
        set(handles.text_decoy_unit_G_jt,'enable','on');
        set(handles.text_decoy_title_G_rr,'enable','on');
        set(handles.edit_decoy_G_rr,'enable','on',...
            'string',num2str(data.C.decoy(1).G_rr));
        set(handles.text_decoy_unit_G_rr,'enable','on');
        set(handles.text_decoy_title_F,'enable','on');
        set(handles.edit_decoy_F,'enable','on',...
            'string',num2str(data.C.decoy(1).F));
        set(handles.text_decoy_unit_F,'enable','on');
        set(handles.edit_decoy_RCS,...
            'string',num2str(data.C.decoy(1).RCS));
        
        
        set(handles.text_ship_title_V,'enable','on');
        set(handles.edit_ship_V,'enable','on',...
            'string',num2str(data.C.ship(1).V));
        set(handles.text_ship_unit_V,'enable','on');
        set(handles.text_ship_title_psi,'enable','on');
        set(handles.edit_ship_psi,'enable','on',...
            'string',num2str(data.C.ship(1).psi*r2d));
        set(handles.text_ship_unit_psi,'enable','on');
        set(handles.text_ship_title_RCS,'enable','on');
        set(handles.edit_ship_RCS,'enable','on',...
            'string',num2str(data.C.ship(1).RCS));
        set(handles.text_ship_unit_RCS,'enable','on');
        
        if sys.flag_MC == 0
            set(handles.text_missile_title_itN,'enable','off')
            set(handles.edit_missile_itN,'enable','off')
            set(handles.text_missile_unit_itN,'enable','off')
            set(handles.text_missile_title_R,'enable','off')
            set(handles.edit_missile_R,'enable','off')
            set(handles.text_missile_unit_R,'enable','off')
            set(handles.text_missile_title_theta,'enable','off')
            set(handles.edit_missile_theta,'enable','off')
            set(handles.text_missile_unit_theta,'enable','off')
            set(handles.text_missile_title_dtheta1,'enable','off')
            set(handles.edit_missile_dtheta1,'enable','off')
            set(handles.text_missile_unit_dtheta1,'enable','off')
            set(handles.text_missile_title_dtheta2,'enable','off')
            set(handles.edit_missile_dtheta2,'enable','off')
            set(handles.text_missile_unit_dtheta2,'enable','off')
        else
            set(handles.text_missile_title_itN,'enable','on')
            set(handles.edit_missile_itN,'enable','on',...
                'string',num2str(data.iter.N))
            set(handles.text_missile_unit_itN,'enable','on')
            set(handles.text_missile_title_R,'enable','on')
            set(handles.edit_missile_R,'enable','on',...
                'string',num2str(data.iter.R))
            set(handles.text_missile_unit_R,'enable','on')
            set(handles.text_missile_title_theta,'enable','on')
            set(handles.edit_missile_theta,'enable','inactive',...
                'string','0:ΔΘ1:2π')
            set(handles.text_missile_unit_theta,'enable','on')
            set(handles.text_missile_title_dtheta1,'enable','on')
            set(handles.edit_missile_dtheta1,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta1,'enable','on')
            set(handles.text_missile_title_dtheta2,'enable','on')
            set(handles.edit_missile_dtheta2,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta2,'enable','on')
        end
    case 4
        set(handles.text_missile_title_N,'enable','on',...
            'string','미사일 수(최대 3기):');
        set(handles.edit_missile_N,'enable','on',...
            'string',num2str(data.C.missile(1).N));
        set(handles.text_missile_unit_N,'enable','on');
        set(handles.text_missile_title_No,'enable','on');
        set(handles.popupmenu_missile_No,'enable','on',...
            'string',num2str([1:data.C.missile(1).N]'));
        set(handles.text_missile_unit_No,'enable','on');
        set(handles.text_missile_title_X,'enable','on');
        set(handles.edit_missile_X,'enable','on',...
            'string',num2str(data.C.missile(1).X));
        set(handles.text_missile_unit_X,'enable','on');
        set(handles.text_missile_title_Y,'enable','on');
        set(handles.edit_missile_Y,'enable','on',...
            'string',num2str(data.C.missile(1).Y));
        set(handles.text_missile_unit_Y,'enable','on');
        set(handles.text_missile_title_Z,'enable','on');
        set(handles.edit_missile_Z,'enable','on',...
            'string',num2str(data.C.missile(1).Z));
        set(handles.text_missile_unit_Z,'enable','on');
        set(handles.text_missile_title_V,'enable','on');
        set(handles.edit_missile_V,'enable','on',...
            'string',num2str(data.C.missile(1).V));
        set(handles.text_missile_unit_V,'enable','on');
        set(handles.text_missile_title_psi,'enable','on');
        set(handles.edit_missile_psi,'enable','on',...
            'string',num2str(data.C.missile(1).psi*r2d));
        set(handles.text_missile_unit_psi,'enable','on');
        set(handles.text_missile_title_P_rt,'enable','on');
        set(handles.edit_missile_P_rt,'enable','on',...
            'string',num2str(data.C.missile(1).P_rt*10^6));
        set(handles.text_missile_unit_P_rt,'enable','on');
        set(handles.text_missile_title_G_rt,'enable','on');
        set(handles.edit_missile_G_rt,'enable','on',...
            'string',num2str(data.C.missile(1).G_rt));
        set(handles.text_missile_unit_G_rt,'enable','on');
        set(handles.text_missile_title_G_rr,'enable','on');
        set(handles.edit_missile_G_rr,'enable','on',...
            'string',num2str(data.C.missile(1).G_rr));
        set(handles.text_missile_unit_G_rr,'enable','on');
        set(handles.text_missile_title_F,'enable','on');
        set(handles.edit_missile_F,'enable','on',...
            'string',num2str(data.C.missile(1).F));
        set(handles.text_missile_unit_F,'enable','on');
        set(handles.text_missile_title_FoV_lim,'enable','on');
        set(handles.edit_missile_FoV_lim,'enable','on',...
            'string',num2str(data.C.missile(1).FoV_lim*r2d));
        set(handles.text_missile_unit_FoV_lim,'enable','on');
        
        set(handles.text_decoy_title_N,'enable','on',...
            'string','기만기(최대 20기):');
        set(handles.edit_decoy_N,'enable','on',...
            'string',num2str(data.C.decoy(1).N));
        set(handles.text_decoy_unit_N,'enable','on');
        set(handles.text_decoy_title_No,'enable','on');
        set(handles.popupmenu_decoy_No,'enable','on',...
            'string',num2str([1:data.C.decoy(1).N]'));
        set(handles.text_decoy_unit_No,'enable','on');
        set(handles.text_decoy_title_V,'enable','on');
        set(handles.edit_decoy_V,'enable','on',...
            'string',num2str(data.C.decoy(1).V));
        set(handles.text_decoy_unit_V,'enable','on');
        set(handles.text_decoy_title_psi,'enable','on');
        set(handles.edit_decoy_psi,'enable','on',...
            'string',num2str(data.C.decoy(1).lau_psi*r2d));
        set(handles.text_decoy_unit_psi,'enable','on');
        set(handles.text_decoy_title_Z,'enable','on');
        set(handles.edit_decoy_Z,'enable','on',...
            'string',num2str(data.C.decoy(1).Z));
        set(handles.text_decoy_unit_Z,'enable','on');

        set(handles.text_decoy_title_P_jt,'enable','on');
        set(handles.edit_decoy_P_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).P_jt*10^6));
        set(handles.text_decoy_unit_P_jt,'enable','on');
        set(handles.text_decoy_title_G_jt,'enable','on');
        set(handles.edit_decoy_G_jt,'enable','on',...
            'string',num2str(data.C.decoy(1).G_jt));
        set(handles.text_decoy_unit_G_jt,'enable','on');
        set(handles.text_decoy_title_G_rr,'enable','on');
        set(handles.edit_decoy_G_rr,'enable','on',...
            'string',num2str(data.C.decoy(1).G_rr));
        set(handles.text_decoy_unit_G_rr,'enable','on');
        set(handles.text_decoy_title_F,'enable','on');
        set(handles.edit_decoy_F,'enable','on',...
            'string',num2str(data.C.decoy(1).F));
        set(handles.text_decoy_unit_F,'enable','on');
        set(handles.edit_decoy_RCS,...
            'string',num2str(data.C.decoy(1).RCS));
        

        set(handles.text_ship_title_V,'enable','on');
        set(handles.edit_ship_V,'enable','on',...
            'string',num2str(data.C.ship(1).V));
        set(handles.text_ship_unit_V,'enable','on');
        set(handles.text_ship_title_psi,'enable','on');
        set(handles.edit_ship_psi,'enable','on',...
            'string',num2str(data.C.ship(1).psi*r2d));
        set(handles.text_ship_unit_psi,'enable','on');
        set(handles.text_ship_title_RCS,'enable','on');
        set(handles.edit_ship_RCS,'enable','on',...
            'string',num2str(data.C.ship(1).RCS));
        set(handles.text_ship_unit_RCS,'enable','on');
        
        if sys.flag_MC == 0
            set(handles.text_missile_title_itN,'enable','off')
            set(handles.edit_missile_itN,'enable','off')
            set(handles.text_missile_unit_itN,'enable','off')
            set(handles.text_missile_title_R,'enable','off')
            set(handles.edit_missile_R,'enable','off')
            set(handles.text_missile_unit_R,'enable','off')
            set(handles.text_missile_title_theta,'enable','off')
            set(handles.edit_missile_theta,'enable','off')
            set(handles.text_missile_unit_theta,'enable','off')
            set(handles.text_missile_title_dtheta1,'enable','off')
            set(handles.edit_missile_dtheta1,'enable','off')
            set(handles.text_missile_unit_dtheta1,'enable','off')
            set(handles.text_missile_title_dtheta2,'enable','off')
            set(handles.edit_missile_dtheta2,'enable','off')
            set(handles.text_missile_unit_dtheta2,'enable','off')
        else
            set(handles.text_missile_title_itN,'enable','on')
            set(handles.edit_missile_itN,'enable','on',...
                'string',num2str(data.iter.N))
            set(handles.text_missile_unit_itN,'enable','on')
            set(handles.text_missile_title_R,'enable','on')
            set(handles.edit_missile_R,'enable','on',...
                'string',num2str(data.iter.R))
            set(handles.text_missile_unit_R,'enable','on')
            set(handles.text_missile_title_theta,'enable','on')
            set(handles.edit_missile_theta,'enable','inactive',...
                'string','0:ΔΘ1:2π')
            set(handles.text_missile_unit_theta,'enable','on')
            set(handles.text_missile_title_dtheta1,'enable','on')
            set(handles.edit_missile_dtheta1,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta1,'enable','on')
            set(handles.text_missile_title_dtheta2,'enable','on')
            set(handles.edit_missile_dtheta2,'enable','on',...
                'string',num2str(data.iter.dtheta1*r2d))
            set(handles.text_missile_unit_dtheta2,'enable','on')
        end
    case 5
        set(handles.text_missile_title_N,'enable','on',...
            'string','미사일 수(최대 3기):');
        set(handles.edit_missile_N,'enable','on');
        set(handles.text_missile_unit_N,'enable','on');
        set(handles.text_missile_title_No,'enable','on');
        set(handles.popupmenu_missile_No,'enable','on');
        set(handles.text_missile_unit_No,'enable','on');
        set(handles.text_missile_title_X,'enable','on');
        set(handles.edit_missile_X,'enable','on');
        set(handles.text_missile_unit_X,'enable','on');
        set(handles.text_missile_title_Y,'enable','on');
        set(handles.edit_missile_Y,'enable','on');
        set(handles.text_missile_unit_Y,'enable','on');
        set(handles.text_missile_title_Z,'enable','on');
        set(handles.edit_missile_Z,'enable','on');
        set(handles.text_missile_unit_Z,'enable','on');
        set(handles.text_missile_title_V,'enable','on');
        set(handles.edit_missile_V,'enable','on');
        set(handles.text_missile_unit_V,'enable','on');
        set(handles.text_missile_title_psi,'enable','on');
        set(handles.edit_missile_psi,'enable','on');
        set(handles.text_missile_unit_psi,'enable','on');
        set(handles.text_missile_title_P_rt,'enable','on');
        set(handles.edit_missile_P_rt,'enable','on');
        set(handles.text_missile_unit_P_rt,'enable','on');
        set(handles.text_missile_title_G_rt,'enable','on');
        set(handles.edit_missile_G_rt,'enable','on');
        set(handles.text_missile_unit_G_rt,'enable','on');
        set(handles.text_missile_title_G_rr,'enable','on');
        set(handles.edit_missile_G_rr,'enable','on');
        set(handles.text_missile_unit_G_rr,'enable','on');
        set(handles.text_missile_title_F,'enable','on');
        set(handles.edit_missile_F,'enable','on');
        set(handles.text_missile_unit_F,'enable','on');
        set(handles.text_missile_title_FoV_lim,'enable','on');
        set(handles.edit_missile_FoV_lim,'enable','on');
        set(handles.text_missile_unit_FoV_lim,'enable','on');
        
        set(handles.text_decoy_title_N,'enable','off',...
            'string','기만기 수(최대 1기):');
        set(handles.edit_decoy_N,'enable','off',...
            'string','1');
        set(handles.text_decoy_unit_N,'enable','off');
        set(handles.text_decoy_title_No,'enable','off');
        set(handles.popupmenu_decoy_No,'enable','off');
        set(handles.text_decoy_unit_No,'enable','off');
        set(handles.text_decoy_title_V,'enable','on');
        set(handles.edit_decoy_V,'enable','on');
        set(handles.text_decoy_unit_V,'enable','on');
        set(handles.text_decoy_title_psi,'enable','on');
        set(handles.edit_decoy_psi,'enable','on');
        set(handles.text_decoy_unit_psi,'enable','on');
        set(handles.text_decoy_title_Z,'enable','on');
        set(handles.edit_decoy_Z,'enable','on',...
            'string','30');
        set(handles.text_decoy_unit_Z,'enable','on');
        set(handles.text_decoy_title_P_jt,'enable','on');
        set(handles.edit_decoy_P_jt,'enable','on');
        set(handles.text_decoy_unit_P_jt,'enable','on');
        set(handles.text_decoy_title_G_jt,'enable','on');
        set(handles.edit_decoy_G_jt,'enable','on');
        set(handles.text_decoy_unit_G_jt,'enable','on');
        set(handles.text_decoy_title_G_rr,'enable','on');
        set(handles.edit_decoy_G_rr,'enable','on');
        set(handles.text_decoy_unit_G_rr,'enable','on');
        set(handles.text_decoy_title_F,'enable','on');
        set(handles.edit_decoy_F,'enable','on');
        set(handles.text_decoy_unit_F,'enable','on');
        
        set(handles.text_ship_title_V,'enable','on');
        set(handles.edit_ship_V,'enable','on');
        set(handles.text_ship_unit_V,'enable','on');
        set(handles.text_ship_title_psi,'enable','on');
        set(handles.edit_ship_psi,'enable','on');
        set(handles.text_ship_unit_psi,'enable','on');
        set(handles.text_ship_title_RCS,'enable','on');
        set(handles.edit_ship_RCS,'enable','on');
        set(handles.text_ship_unit_RCS,'enable','on');
    otherwise
end