function  [handles] = TimerSetting(handles)
dt_timer = 0.1;
handles.GUIStartTime = clock;
handles.Timer_main = timer('ExecutionMode','fixedRate',...
     'Period', dt_timer,...
     'BusyMode','queue',...
     'timerfcn', {@Timer_mainFcn,handles});

dt_vis = 0.1;
handles.Timer_vis = timer('ExecutionMode','fixedRate',...
     'Period', dt_vis,...
     'BusyMode','queue',...
     'timerfcn', {@Timer_visFcn,handles});